os: linux
dist: focal
language: c
compiler: 
- gcc

before_install:
  - sudo apt update

script:
  - wget https://raw.githubusercontent.com/lordmilko/i686-elf-tools/master/i686-elf-tools.sh
  - chmod ./i686-elf-tools.sh
  - ./i686-elf-tools.sh
  - make all

